version: "3"
services:
  spark:
    image: spark
    container_name: spark
    user: root
    environment:
      - HOME=/root

    ports:
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
      - "8888:8888"
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    command: >
      bash -c "
      pip install jupyterlab &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
      "
